"""Add current_sync_records and lifetime_records_processed

Revision ID: 0d4d3b11c194
Revises: 539acdab8e48
Create Date: 2026-07-30 19:55:18.982987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4d3b11c194'
down_revision: Union[str, None] = '539acdab8e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_sync_states_v2', sa.Column('current_sync_records', sa.Integer(), nullable=False))
    op.add_column('crm_sync_states_v2', sa.Column('lifetime_records_processed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_sync_states_v2', 'lifetime_records_processed')
    op.drop_column('crm_sync_states_v2', 'current_sync_records')
    # ### end Alembic commands ###
