from typing import List, Optional, Protocol, Dict, Any
from uuid import UUID

from app.modules.enterprise_intelligence.domain.company_intelligence import CompanyIntelligence
from app.modules.enterprise_intelligence.domain.contact_intelligence import ContactIntelligence
from app.modules.enterprise_intelligence.domain.technology_intelligence import TechnologyIntelligence
from app.modules.enterprise_intelligence.domain.buying_committee import BuyingCommitteeIntelligence
from app.modules.enterprise_intelligence.domain.funding_intelligence import FundingIntelligence
from app.modules.enterprise_intelligence.domain.hiring_intelligence import HiringIntelligence
from app.modules.enterprise_intelligence.domain.executive_intelligence import ExecutiveIntelligence
from app.modules.enterprise_intelligence.domain.competitive_intelligence import CompetitiveIntelligence
from app.modules.enterprise_intelligence.domain.market_intelligence import MarketIntelligence
from app.modules.enterprise_intelligence.domain.industry_intelligence import IndustryIntelligence
from app.modules.enterprise_intelligence.domain.signal_intelligence import SignalIntelligence, NormalizedSignal
from app.modules.enterprise_intelligence.domain.identity_resolution import CanonicalEntity, CompanyIdentity, ContactIdentity

class CompanyIntelligenceRepository(Protocol):
    async def get_by_id(self, tenant_id: UUID, intelligence_id: UUID) -> Optional[CompanyIntelligence]: ...
    async def get_by_domain(self, tenant_id: UUID, domain: str) -> Optional[CompanyIntelligence]: ...
    async def save(self, intelligence: CompanyIntelligence) -> CompanyIntelligence: ...

class CompanyIntelligenceProvider(Protocol):
    async def fetch_company_data(self, domain: str) -> CompanyIntelligence: ...

class ContactIntelligenceRepository(Protocol):
    async def get_by_id(self, tenant_id: UUID, intelligence_id: UUID) -> Optional[ContactIntelligence]: ...
    async def get_by_email(self, tenant_id: UUID, email: str) -> Optional[ContactIntelligence]: ...
    async def save(self, intelligence: ContactIntelligence) -> ContactIntelligence: ...

class ContactIntelligenceProvider(Protocol):
    async def fetch_contact_data(self, email: str) -> ContactIntelligence: ...

class TechnologyIntelligenceRepository(Protocol):
    async def get_by_company_id(self, tenant_id: UUID, company_id: UUID) -> Optional[TechnologyIntelligence]: ...
    async def save(self, intelligence: TechnologyIntelligence) -> TechnologyIntelligence: ...

class TechnologyIntelligenceProvider(Protocol):
    async def fetch_technology_data(self, domain: str) -> TechnologyIntelligence: ...

class BuyingCommitteeRepository(Protocol):
    async def get_by_company_id(self, tenant_id: UUID, company_id: UUID) -> Optional[BuyingCommitteeIntelligence]: ...
    async def save(self, intelligence: BuyingCommitteeIntelligence) -> BuyingCommitteeIntelligence: ...

class BuyingCommitteeProvider(Protocol):
    async def fetch_committee_data(self, company_id: UUID) -> BuyingCommitteeIntelligence: ...

class FundingIntelligenceRepository(Protocol):
    async def get_by_company_id(self, tenant_id: UUID, company_id: UUID) -> Optional[FundingIntelligence]: ...
    async def save(self, intelligence: FundingIntelligence) -> FundingIntelligence: ...

class FundingIntelligenceProvider(Protocol):
    async def fetch_funding_data(self, domain: str) -> FundingIntelligence: ...

class HiringIntelligenceRepository(Protocol):
    async def get_by_company_id(self, tenant_id: UUID, company_id: UUID) -> Optional[HiringIntelligence]: ...
    async def save(self, intelligence: HiringIntelligence) -> HiringIntelligence: ...

class HiringIntelligenceProvider(Protocol):
    async def fetch_hiring_data(self, domain: str) -> HiringIntelligence: ...

class ExecutiveIntelligenceRepository(Protocol):
    async def get_by_company_id(self, tenant_id: UUID, company_id: UUID) -> Optional[ExecutiveIntelligence]: ...
    async def save(self, intelligence: ExecutiveIntelligence) -> ExecutiveIntelligence: ...

class ExecutiveIntelligenceProvider(Protocol):
    async def fetch_executive_data(self, company_id: UUID) -> ExecutiveIntelligence: ...

class CompetitiveIntelligenceRepository(Protocol):
    async def get_by_company_id(self, tenant_id: UUID, company_id: UUID) -> Optional[CompetitiveIntelligence]: ...
    async def save(self, intelligence: CompetitiveIntelligence) -> CompetitiveIntelligence: ...

class CompetitiveIntelligenceProvider(Protocol):
    async def fetch_competitive_data(self, domain: str) -> CompetitiveIntelligence: ...

class MarketIntelligenceRepository(Protocol):
    async def get_by_company_id(self, tenant_id: UUID, company_id: UUID) -> Optional[MarketIntelligence]: ...
    async def save(self, intelligence: MarketIntelligence) -> MarketIntelligence: ...

class MarketIntelligenceProvider(Protocol):
    async def fetch_market_data(self, industry: str) -> MarketIntelligence: ...

class IndustryIntelligenceRepository(Protocol):
    async def get_by_industry(self, tenant_id: UUID, industry_name: str) -> Optional[IndustryIntelligence]: ...
    async def save(self, intelligence: IndustryIntelligence) -> IndustryIntelligence: ...

class IndustryIntelligenceProvider(Protocol):
    async def fetch_industry_data(self, industry_name: str) -> IndustryIntelligence: ...

class SignalIntelligenceRepository(Protocol):
    async def get_by_company_id(self, tenant_id: UUID, company_id: UUID) -> Optional[SignalIntelligence]: ...
    async def save(self, intelligence: SignalIntelligence) -> SignalIntelligence: ...

class SignalProvider(Protocol):
    async def fetch_signals(self, domain: str) -> List[NormalizedSignal]: ...

class IdentityResolutionRepository(Protocol):
    async def get_by_id(self, tenant_id: UUID, entity_id: UUID) -> Optional[CanonicalEntity]: ...
    async def get_by_primary_identifier(self, tenant_id: UUID, entity_type: str, identifier: str) -> Optional[CanonicalEntity]: ...
    async def save(self, identity: CanonicalEntity) -> CanonicalEntity: ...
    async def find_duplicates(self, tenant_id: UUID, entity_type: str) -> List[CanonicalEntity]: ...

class IdentityProvider(Protocol):
    async def verify_identity(self, entity_type: str, identifier: str) -> Dict[str, Any]: ...
