"""
Intelligence feed routes.
The core product: surfaces high-probability accounts with explanations.
"""
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks, Query
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.api.auth import CurrentUser
from app.db.session import get_db
from app.models import (
    Company, IntelligenceFeedItem, Signal,
    Contact, CompanyStatus, BuyingWindowLabel,
)

router = APIRouter(prefix="/feed", tags=["intelligence-feed"])


class DismissRequest(BaseModel):
    company_id: str


def _serialize_feed_item(item: IntelligenceFeedItem, company: Company, contacts: list[Contact]) -> dict:
    primary = next((c for c in contacts if c.is_primary), contacts[0] if contacts else None)
    return {
        "id": str(item.id),
        "company": {
            "id": str(company.id),
            "name": company.name,
            "domain": company.domain,
            "industry": company.industry,
            "employee_count": company.employee_count,
            "employee_range": company.employee_range,
            "location": " ".join(filter(None, [
                company.location_city, company.location_state, company.location_country
            ])),
            "funding_stage": company.last_funding_stage,
            "funding_total_usd": company.funding_total_usd,
            "technologies": company.technologies[:10] if company.technologies else [],
            "linkedin_url": company.linkedin_url,
            "website": company.website,
        },
        "intelligence": {
            "composite_score": round(item.composite_score, 3),
            "buying_window": item.buying_window,
            "buying_window_confidence": round(item.buying_window_confidence, 3),
            "signal_summary": item.signal_summary,
            "buying_window_reasoning": item.buying_window_reasoning,
            "recommended_angle": item.recommended_angle,
            "top_signals": item.top_signals,
            "similar_converted_companies": item.similar_converted_companies,
        },
        "recommended_contact": {
            "title": item.recommended_contact_title,
            "name": primary.full_name if primary else None,
            "email": primary.email if primary else None,
            "linkedin_url": primary.linkedin_url if primary else None,
        } if primary else None,
        "generated_at": item.generated_at.isoformat(),
        "expires_at": item.expires_at.isoformat(),
        "is_dismissed": item.is_dismissed,
    }


@router.get("")
def get_feed(
    current_user: CurrentUser,
    db: Session = Depends(get_db),
    buying_window: Optional[str] = Query(None, description="Filter: hot, warm, watch"),
    min_score: float = Query(0.0, ge=0.0, le=1.0),
    limit: int = Query(20, ge=1, le=100),
    offset: int = Query(0, ge=0),
):
    """
    Get the Account Intelligence Feed for the current workspace.
    Returns accounts ordered by composite score descending.
    Pre-generated by nightly batch; refreshes on demand if stale.
    """
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)

    query = (
        db.query(IntelligenceFeedItem)
        .filter(
            IntelligenceFeedItem.workspace_id == current_user.workspace_id,
            IntelligenceFeedItem.is_dismissed == False,
            IntelligenceFeedItem.expires_at > now,
            IntelligenceFeedItem.composite_score >= min_score,
        )
    )

    if buying_window:
        query = query.filter(IntelligenceFeedItem.buying_window == buying_window)

    total = query.count()
    items = (
        query
        .order_by(IntelligenceFeedItem.composite_score.desc())
        .offset(offset)
        .limit(limit)
        .all()
    )

    results = []
    for item in items:
        company = db.get(Company, item.company_id)
        if not company:
            continue
        contacts = db.query(Contact).filter_by(company_id=company.id).all()
        results.append(_serialize_feed_item(item, company, contacts))

    return {
        "total": total,
        "offset": offset,
        "limit": limit,
        "items": results,
        "buying_window_summary": _buying_window_summary(db, current_user.workspace_id),
    }


@router.get("/company/{company_id}")
def get_company_intelligence(
    company_id: str,
    current_user: CurrentUser,
    db: Session = Depends(get_db),
):
    """Get full intelligence detail for a specific company."""
    company = db.get(Company, company_id)
    if not company or str(company.workspace_id) != str(current_user.workspace_id):
        raise HTTPException(status_code=404, detail="Company not found")

    item = (
        db.query(IntelligenceFeedItem)
        .filter_by(company_id=company_id)
        .order_by(IntelligenceFeedItem.generated_at.desc())
        .first()
    )

    signals = (
        db.query(Signal)
        .filter_by(company_id=company_id)
        .order_by(Signal.detected_at.desc())
        .all()
    )

    contacts = db.query(Contact).filter_by(company_id=company_id).all()

    return {
        "company": {
            "id": str(company.id),
            "name": company.name,
            "domain": company.domain,
            "industry": company.industry,
            "employee_count": company.employee_count,
            "location": " ".join(filter(None, [
                company.location_city, company.location_state, company.location_country
            ])),
            "description": company.description,
            "technologies": company.technologies,
            "funding_stage": company.last_funding_stage,
            "funding_total_usd": company.funding_total_usd,
            "linkedin_url": company.linkedin_url,
            "website": company.website,
            "status": company.status,
            "composite_score": company.composite_score,
            "buying_window": company.buying_window,
            "last_scored_at": company.last_scored_at.isoformat() if company.last_scored_at else None,
        },
        "intelligence": {
            "signal_summary": item.signal_summary if item else None,
            "buying_window_reasoning": item.buying_window_reasoning if item else None,
            "recommended_angle": item.recommended_angle if item else None,
            "similar_converted_companies": item.similar_converted_companies if item else [],
        },
        "signals": [
            {
                "id": str(s.id),
                "type": s.signal_type,
                "source": s.signal_source,
                "title": s.title,
                "description": s.description,
                "url": s.url,
                "strength": round(s.decayed_strength, 3),
                "detected_at": s.detected_at.isoformat(),
            }
            for s in signals
        ],
        "contacts": [
            {
                "id": str(c.id),
                "name": c.full_name,
                "title": c.title,
                "email": c.email,
                "email_status": c.email_status,
                "linkedin_url": c.linkedin_url,
                "is_primary": c.is_primary,
            }
            for c in contacts
        ],
    }


@router.post("/refresh")
def refresh_feed(
    current_user: CurrentUser,
    db: Session = Depends(get_db),
    background_tasks: BackgroundTasks = None,
):
    """
    Trigger on-demand feed refresh for the workspace.
    Runs as background task; returns immediately.
    """
    from app.workers.tasks import generate_feed_for_workspace
    generate_feed_for_workspace.delay(str(current_user.workspace_id), force_refresh=True)
    return {"status": "refresh_queued", "workspace_id": str(current_user.workspace_id)}


@router.post("/dismiss")
def dismiss_company(
    req: DismissRequest,
    current_user: CurrentUser,
    db: Session = Depends(get_db),
):
    """Mark a company as dismissed from the feed (won't reappear until next refresh)."""
    item = (
        db.query(IntelligenceFeedItem)
        .filter_by(
            company_id=req.company_id,
            workspace_id=current_user.workspace_id,
        )
        .first()
    )
    if not item:
        raise HTTPException(status_code=404, detail="Feed item not found")

    item.is_dismissed = True
    db.commit()
    return {"success": True}


def _buying_window_summary(db: Session, workspace_id) -> dict:
    """Count of companies per buying window label."""
    from sqlalchemy import func
    from datetime import datetime, timezone

    now = datetime.now(timezone.utc)
    rows = (
        db.query(
            IntelligenceFeedItem.buying_window,
            func.count(IntelligenceFeedItem.id).label("count"),
        )
        .filter(
            IntelligenceFeedItem.workspace_id == workspace_id,
            IntelligenceFeedItem.is_dismissed == False,
            IntelligenceFeedItem.expires_at > now,
        )
        .group_by(IntelligenceFeedItem.buying_window)
        .all()
    )
    summary = {"hot": 0, "warm": 0, "watch": 0, "cold": 0}
    for row in rows:
        summary[row.buying_window] = row.count
    return summary
